name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: zulu@1.8
    - uses: coursier/cache-action@v3
    - run: |
        wget https://raw.githubusercontent.com/lefou/millw/main/millw && chmod +x millw
        ./millw cardan.compile
        ./millw cardan.assembly
        mv out/cardan/assembly.dest/out.jar cardan.assembly.jar
    - uses: actions/upload-artifact@v3
      with:
        name: assembly
        path: cardan.assembly.jar
